### ISSUE TITLE
Missing file "linear.dat"

### ISSUE THREAD

**Issue by lucaslucaslucaslu** [hjkgrp/molSimplify#235]
Hi, I tried to run
`molsimplify -cores Fe -lig '[N+](=O)([O-])[O-]' -smicat [[3, 4]] -coord 2 -ligocc 1 -spin 1 -rundir ms_dummy`
and get
`FileNotFoundError: [Errno 2] No such file or directory: '/home/usr/.conda/envs/myenv/lib/python3.11/site-packages/molSimplify/Data/linear.dat'`.

I didn't find this specific file in the repo, and it doesn't really work if I simply rename li.dat to linear.dat or make a copy of li.dat

I'm just wondering if there is anything I missed, thanks!

**Comment by dbkchu** [comment]
Hi,

Thank you for pointing out this error. It appears that there was a typo in the list of default geometry names for the two and three coordinate geometries. This has now been fixed, but this code will still not run since molSimplify does not support attaching a bidentate ligand to a linear geometry.

If you would really like only one ligand attached, I would recommend making a tetrahedral structure with the ligand and then manually deleting the second ligand.

To make a tetrahedral structure, you could run:
`molsimplify -cores Fe -lig '[N+](=O)([O-])[O-]' -smicat [[3, 4]] -coord 4 -ligocc 2 -spin 1`

We will look into adding the ability to attach a bidentate ligand to a linear geometry, but this may take a while.
