### ISSUE TITLE
Custom ligands with charges

### ISSUE THREAD

**Issue by HelloJocelynLu** [hjkgrp/molSimplify#26]
Hi,
It is a pretty powerful package and I'm happy to find and use it!
When I followed tutorial 10: Adding ligands to molSimplify and would like to add a ligand with -1 charge. But I figure out that I don't have the option.
In source code addtodb.py, when we add a ligand:
*sminame+':'+sminame+'.smi,'+shortname+','+css+','+grp+','+ffopt*
this line would be added to ligands.dict without charge information. Is it possible to add an input option for charge or identify charge automatically from input files?
Many thanks!
Jocelyn

**Comment by adityanandy** [comment]
Hi,

Thanks for using molSimplify! 

Our apologies for the lack of proper documentation here, but the _charge is already read by default_, and the charge in the dictionary is merely present for ease of charge identification by the user (which is why it is not written by default in the addtodb script). For instance, if you add a SMILES string (which contains charge information) to the database, that SMILES string is stored as a .smi file in the Ligands/ folder. This is later read, and the charge is obtained via openbabel (by loading in an OBMol object). The same is true if you have an .mol file, which stores charge information. Thus if you wish to add a ligand by referencing a file (as opposed to using a SMILES string), we recommend using the .mol format, which stores charge information as well. 

However, for consistency and maintenance of the ligands.dict file (in the Ligands/ folder), I have adjusted the script to store the charge automatically (as you requested). If you cloned our repo from source `[bd9f47eb](https://github.com/hjkgrp/molSimplify/commit/bd9f47eb061959992125eba755f39afc66acfd10)` will have this change.
