### ISSUE TITLE
Identification of solvent in MOF_descriptors.py

### ISSUE THREAD

**Issue by BurnerJ** [hjkgrp/molSimplify#40]
Hi there,

I noticed there are some instances where molSimplify is failing to featurize some structures due to solvent being present in the structure. In my case, I have found this to be flagging structures incorrectly, I have attached an example .cif file (as a txt file) where this has occurred. I was curious whether this behaviour is intended or if it is a bug?

When running get_MOF_descriptors function on this cif, I receive the following output in FailedStructures.log:

> Failed to featurize DB5-hypotheticalMOF_1000051_0_0_3_26_9_1: solvent molecules
[DB5-hypotheticalMOF_1000051_0_0_3_26_9_1.txt](https://github.com/hjkgrp/molSimplify/files/7213642/DB5-hypotheticalMOF_1000051_0_0_3_26_9_1.txt)

**Comment by adityanandy** [comment]
Hi Jake,

This is because of how some of the linkers were placed in the cif files of the structure. It's detected as "solvent" because there is a floating linker that is not connected to the metals that are present in the unit cell. Thus, this is the expected behavior -- it is not a bug. Because we have to interpret the connectivity (since cifs do not contain connectivity information), we cannot know that that floating linker is connected to a metal, because it is not in this cell. Indeed, this happens to a significant fraction of the Wilmer database, which is why we did not use it for analysis in the manuscript.

Let us know if any of this doesn't make sense.

Sincerely,
Aditya

**Comment by BurnerJ** [comment]
Hi Aditya,

Thanks for clearing up the issue. I figured since molSimplify works off a periodic graph, then this issue wouldn't be encountered, but perhaps I'm misunderstanding the problem you're describing.

Jake

**Comment by adityanandy** [comment]
Hi Jake,

Yes, you are correct about the periodic graph, but you're misunderstanding where the issue comes. The issue is coming from interpreting the graph itself. If we had the ground truth graph, you are right that the issue would not be encountered. From the cif file, when we interpret the connectivity, one of the linkers is interpreted to be *NOT* connected to any inorganic SBU. Because there are no bonds with any metal, it is a "floating" subgraph within the periodic graph that is not connected to anything else. That's why it gets identified as "solvent" (because its a floating organic molecule that is not connected to any metals in the periodic graph). If you have a way to fix this in the graph you can feel free to submit a pull request.
