### ISSUE TITLE
Critical typo in test helperFuncs.py

### ISSUE THREAD

**Issue by ralf-meyer** [hjkgrp/molSimplify#47]
There is a minor typo on line 133 in helperFuncs.py:
`pssLG = False` instead of `passLG = False`

This causes a false negative (or positive?) test result. Fixing the typo breaks `test_example_3.py`. I have no idea what this test is supposed to check for. Since the original contributors are no longer here: Can anyone else help me out?

**Comment by ralf-meyer** [comment]
On a related note: `test_bidentate.py` and `test_example_5.py` both fail on my M1 Mac. Can anyone confirm this behavior for me?

**Comment by naveenarun** [comment]
> On a related note: `test_bidentate.py` and `test_example_5.py` both fail on my M1 Mac. Can anyone confirm this behavior?

This is expected (yet unfortunate) behavior, as the build for M1 Macs uses OpenBabel 3, which doesn't count hydrogens when indexing atoms of a ligand built from a SMILES string. For test_bidentate.py, it uses the input file [bidentate_lig.smi](https://github.com/hjkgrp/molSimplify/blob/f706a2761cdf03416b38350eda1de8417aeb48c7/tests/inputs/bidentate_lig.smi) which has hydrogen-containing ligands. The same is true for [example_5.in](https://github.com/hjkgrp/molSimplify/blob/f706a2761cdf03416b38350eda1de8417aeb48c7/tests/inputs/example_5.in).

For example, with [example_5.in](https://github.com/hjkgrp/molSimplify/blob/f706a2761cdf03416b38350eda1de8417aeb48c7/tests/inputs/example_5.in), in OpenBabel 2 (assuming indexing starts at 1), the position of `n1` in the SMILES string `c1(nn[nH]n1)c1ncccc1` will be `6`, whereas in OpenBabel 3 it will be `5`. This is an issue because the `-smicat 8,6` flag specifies which indices should be considered connecting atoms. OpenBabel2 will correctly call `n1` a connecting atom; OpenBabel 3 will instead choose the second `c1`.

**Comment by naveenarun** [comment]
For test_example_3, I think something weird is happening regardless of whether `passLG` is fixed. In [example_3_noff.in](https://github.com/hjkgrp/molSimplify/blob/f706a2761cdf03416b38350eda1de8417aeb48c7/tests/inputs/example_3_noff.in), it looks like molSimplify distorts `ferrcore.xyz` despite the fact that `ffoption` is set to `no` @chenruduan could you take a look?

<img width="597" alt="image" src="https://user-images.githubusercontent.com/5258974/149432787-68f92c5d-556b-4d01-887d-b67fe4ad8b66.png">

**Comment by chenruduan** [comment]
The reference results of test_example3 is a incorect–someone placed a .xyz file without FFopt as a reference. If the FF is on, the structure breaks apart… It may take some time to see why that is… @ralf-meyer Can you try whether the newly added xtb can fix the optimization? It seems a bit strange on the FF end.

**Comment by ralf-meyer** [comment]
This thread has gotten somewhat out of sync due to yesterdays PR (#49). The issue mentioned by @naveenarun 
> molSimplify distorts `ferrcore.xyz` despite the fact that `ffoption` is set to `no`

has been fixed since I stumbled upon that bug more or less by coincidence. 

The remaining problem is a wrong reference for `example_3.xyz`. As mentioned by @chenruduan force field optimization with MMFF94 breaks the structure (test case fails with wrong number of ligands / atoms per ligand):
<img width="250" alt="result_mmff94" src="https://user-images.githubusercontent.com/7551256/151452082-72ae14c2-63e3-4b20-9c98-e825cc9769c0.png">

While xtb does not destroy the structure:
<img width="250" alt="result_xtb" src="https://user-images.githubusercontent.com/7551256/151451459-7e95d518-1001-4503-b378-8804f188b875.png"> 
I am not sure if this solution is in the "spirit" of the test case.

What was the original intention of this test? 
I guess that it is supposed to test structure generation for multi-atom cores. Which raises the question, what constraints should be applied during such an optimization? Which atoms / bond lengths should be frozen?

**Comment by adityanandy** [comment]
Just going to chime in here with one small detail to answer Ralf's question. I'm fairly certain that this test case was there to go hand-in-hand with the custom core functionalization tutorial: http://hjkgrp.mit.edu/content/molsimplify-tutorial-3-custom-core-functionalization --> which is to ensure that the replig function works

**Comment by ralf-meyer** [comment]
Thank you @adityanandy! I am still confused: There is a separate test case for the tutorial ([test_tutorial_3.py](https://github.com/hjkgrp/molSimplify/blob/b485bac6ccee5eaa4a8d06bc7897f11209a335bf/tests/test_tutorial_3.py)) that is basically just a reduced version of the `ffoption no` version of `test_example_3`

**Comment by adityanandy** [comment]
That is a really good point. I don't remember off of the top of my head why there are both of those. We had a hackathon where we were making test cases for all of the tutorials, so we probably just didnt realize one existed already

**Comment by ralf-meyer** [comment]
PR #52 fixes this issue. For now `test_example_3` is switched from `MMFF94` to `UFF` as this is the simplest fix. However, this choice still leads to a breakup of the ligand, which brings us back to the question: What constraints should be applied here? Which atoms should be considered as "connecting atoms"?
