### ISSUE TITLE
Single atoms listed on GUI as possible ligands, causes error if selected

### ISSUE THREAD

**Issue by dbkchu** [hjkgrp/molSimplify#56]
Looks like structure generation doesn't recognize single atoms and searches for a .mol file
Error message: 
`We can't find the ligand structure file /home/dbkchu/programs/molSimplify/molSimplify/Ligands/hydrogen.mol right now! Something is amiss. Exiting..`

**Comment by gianmarco-terrones** [comment]
Hi @dbkchu, thank you for bringing this to our attention. It looks like the Ligands folder was missing a structure file for hydrogen for some reason. Anyway, I added it now, so structure generation should accept hydrogen. Try a command like `molsimplify -core Ir -oxstate 3 -spin 1 -geometry oct -lig hydrogen -ligocc 6 -coord 6` in the command line to make a homoleptic octahedral transition metal complex with a central iridium atom and 6 coordinated hydrogens.

**Comment by ralf-meyer** [comment]
@gianmarco-terrones According to `ligands.dict` the hydrogen atom in the .mol file should be charged negatively:
`hydrogen:hydrogen.mol,hydrogen,0,build functionalize small,N,-1`

Since this is not the only inconsistency or missing `.mol` file I would suggest adding a test case that checks the whole `ligands.dict` file. In case nobody else volunteers, I should be able to work on this next week.

**Comment by ralf-meyer** [comment]
Current state:

I have added a simple test case and started fixing simple mistakes in `ligands.dict` (see https://github.com/ralf-meyer/molSimplify/tree/update_ligands).

Out of 263 ligands in the dictionary 70 failed the test. For 32 entries there is no corresponding `.xyz`, `.mol`, or `.smi` file, while for the remaining failures there is a discrepancy between the "formal charge" given in `ligands.dict` and the charge reported after loading the ligand.

**Comment by ralf-meyer** [comment]
During the Hackathon Shuwen added most of the missing .mol files from https://cccbdb.nist.gov/mdlmol1.asp

**Comment by ralf-meyer** [comment]
That would be great! Thank you!

**Comment by gianmarco-terrones** [comment]
Done! Ralf added a test case to check the whole ligands.dict file, to make sure geometry files can be loaded and that charges are consistent in the case of `.mol` files. This test script is at `tests/test_ligands.py'. 

Shuwen and Gianmarco added missing `.mol` files and modified `ligands.dict` charge entries in order to ensure the test script passed and that we have consistency. Going forward, we should not have the issue of missing ligand geometry files from `ligands.dict` thanks to the test script that is run whenever a change is pushed to the repo.
